name: CRON Jobs (Réparto)

on:
  schedule:
    # Exécution toutes les 5 minutes
    - cron: '*/5 * * * *'
  
  # Permet aussi de déclencher manuellement le CRON depuis Github
  workflow_dispatch:
    inputs:
      type:
        description: 'Type de CRON (daily ou monthly)'
        required: true
        default: 'daily'
        type: choice
        options:
        - daily
        - monthly

jobs:
  run-cron:
    name: Exécuter les répartitions automatiques
    runs-on: ubuntu-latest
    steps:
      - name: Déterminer l'URL
        id: set-url
        run: |
          if [ "${{ github.event.inputs.type }}" == "monthly" ] || [ "${{ github.event.schedule }}" == "30 0 1 * *" ]; then
            echo "endpoint=monthly" >> $GITHUB_ENV
          else
            echo "endpoint=daily" >> $GITHUB_ENV
          fi

      - name: Ping API
        run: |
          echo "Lancement du CRON : ${{ env.endpoint }}"
          curl -X GET "${{ secrets.PROD_URL }}/api/cron/master" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -f || { echo "Le CRON a échoué"; exit 1; }
